### ISSUE TITLE
Create folder bug

### ISSUE THREAD

**Issue by digimumo** [livewire-filemanager/filemanager#9]
Hi love your UI and file manager. 

I've just installed it to test it but noticed that when you click on the 'add folder' icon and the new folder icon appears. Once you have typed the folder name if you don't press the 'enter' key and instead just click away somewhere on the screen it doesn't 'create' the folder it just stays there until refresh. Could be confusing for users. 

![Screenshot 2024-07-11 100306](https://github.com/livewire-filemanager/filemanager/assets/135252565/5acc1cde-1b81-4353-9e65-828b6671c1b0)

**Comment by bee-interactive** [comment]
Hi @digimumo! Thanks for the feedback, you're right, I will fix this 👍
